### ISSUE TITLE
Photo

### ISSUE THREAD

**Issue by emitanaka** [StatSocAus/ecssc2021-hs#2]
Bio + photo from everyone

**Comment by kevinwang09** [comment]
Done mine in 77acf2f110b131d4fb916bab198ee6e4f29dd0be

**Comment by kevinwang09** [comment]
+ @emitanaka, https://github.com/StatSocAus/ecssc2021-hs/blob/57d667d60cfd92f5493303dc94fbb03900dc91a3/workshop.Rmd#L24
+@PatrickRobotham, https://github.com/StatSocAus/ecssc2021-hs/blob/57d667d60cfd92f5493303dc94fbb03900dc91a3/workshop.Rmd#L41
